# Generated by Django 4.2.5 on 2023-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
