# Generated by Django 4.2.5 on 2023-09-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cities_pettypes_delete_pettype_ad_city_ad_pet_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettypes',
            old_name='pet_type',
            new_name='pet_type_name',
        ),
    ]
