# Generated by Django 4.2.5 on 2023-09-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_pet_type_pettypes_pet_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_breed_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='age',
        ),
        migrations.AddField(
            model_name='ad',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='pet_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pettypes',
            name='pet_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.petbreeds'),
        ),
    ]
