# Generated by Django 4.2.5 on 2023-09-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_petbreeds_remove_ad_age_ad_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(null=True, upload_to='ad_images/'),
        ),
    ]
