# Generated by Django 4.2.5 on 2023-10-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_pettypes_pet_breed_petbreeds_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='pet_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.petbreeds'),
        ),
        migrations.AlterField(
            model_name='petbreeds',
            name='pet_breed_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
