# Generated by Django 4.2.5 on 2023-10-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ad_pet_breed_alter_petbreeds_pet_breed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettypes',
            name='pet_type_image',
            field=models.ImageField(null=True, upload_to='pet_type_images/'),
        ),
    ]
